const INC_CUSTOM='INC_CUSTOM';
const INC='INC';
const DEC='DEC';
const RESET='RESET';
const INC_CUSTOM_2='INC_CUSTOM_2';
const INC_2='INC_2';
const DEC_2='DEC_2';
const RESET_2='RESET_2';
const ON_USERS_LOADED ='ON_USERS_LOADED';
const ON_BAD_TO_ADD ='ON_BAD_TO_ADD';
const ON_BAD_TO_REMOVE ='ON_BAD_TO_REMOVE';
const START_PRODUCTS_LOADING='START_PRODUCTS_LOADING'
const END_PRODUCTS_LOADING='END_PRODUCTS_LOADING'
const SET_PRODUCTS='SET_PRODUCTS'
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST'
const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST'

export {
    INC_CUSTOM,
    INC,
    DEC,
    RESET,
    INC_CUSTOM_2,
    INC_2,
    DEC_2,
    RESET_2,
    ON_USERS_LOADED,
    ON_BAD_TO_ADD,
    ON_BAD_TO_REMOVE,
    START_PRODUCTS_LOADING,
    END_PRODUCTS_LOADING,
    SET_PRODUCTS,
    ADD_PRODUCT_TO_CART,
    REMOVE_PRODUCT_FROM_CART,
    ADD_PRODUCT_TO_WISHLIST,
    REMOVE_PRODUCT_FROM_WISHLIST
}